#! /bin/bash

## dep_setup

## sourcecode ##
# git@git.eg.com:wzc/setup.git 

## Dependencies ##
# git@git.eg.com:soft/platform.git

source ~/common.sh
trap EXIT_CONFIRMATION SIGINT
trap 'ERRTRAP $LINENO' ERR


CMD=`echo $(basename $0)`

if [ $# -lt 2 ];then
	echo -e "缺少参数!\nUsage: $CMD [branch name] [depend_branch_name]\nE.g: dep_setup 2018-07-12  1.0.24"
	exit
#elif ! [[ "$1" =~ ^[1-9]\.[0-9]\.[0-9][0-9]$ ]];then
#	echo -e "参数格式错误!"
#	exit
fi

set -u

#Define Variables
DEFINE_VARIABLES

#Define system path
DEFINE_SYSTEM_PATH

START_TIME=`date "+%Y%m%d-%T"`
BRANCH_NAME=$1
DEPEND_BRANCH_NAME=release_$2
BUILD_DIR=/Data/war/setup/${BRANCH_NAME}

#Create dir if not exist
[ ! -d ${BUILD_DIR} ] && mkdir -p ${BUILD_DIR}


# 更新代码
cd ${SETUP_SOURCE_DIR}

git pull && git checkout ${BRANCH_NAME}
if NEW_COMMIT ${BRANCH_NAME};then
    git pull
fi

# 初始化配置文件
# 该项目配置文件独立在jar包外，故打包时不必考虑环境差异


# 开始构建
cd ${SETUP_SOURCE_DIR}
mvn clean package -Dmaven.test.skip=true

UNALIAS_CP
cp -f ${SETUP_SOURCE_DIR}/web/target/web.jar ${BUILD_DIR}

END_TIME=`date "+%Y%m%d-%T"`

cat >> /Data/logs/deplog/dep_setup.log <<EOF
========================================
Rebuild setup success.

TIME: ${START_TIME}
setup Version: ${BRANCH_NAME}
EOF

exit 0

