#!/bin/bash
# dep_api
# Modified by shidg,20160701


# Define Variables
source ~/common.sh

# 遇到错误即退出脚本
trap 'ERRTRAP $LINENO' ERR
#处理"Ctrl+C"
trap EXIT_CONFIRMATION SIGINT

# Define Variables
DEFINE_VARIABLES 
#Define system path
DEFINE_SYSTEM_PATH

# 有未定义的变量则退出脚本，防止误删根目录
set -u

START_TIME=`date "+%Y%m%d-%T"`

CMD=`echo $(basename $0)`
if [ -z $1 ];then
    echo -e "Usage: $CMD [branch number]\nE.g:   dep_platform 1.0.11"
    exit
fi
set -u

BRANCH_NAME=release_$1
BUILD_DIR=/Data/war/api/branch/${BRANCH_NAME}
MODULE=api



# update source code
GET_READY_FOR_API

#build war packages
   cd ${MANAGE_SOURCE_DIR}/manage-global-api
   mvn clean install -Dmaven.test.skip=true
   cd ${MANAGE_SOURCE_DIR}/wzc-api
   mvn clean package

# create dirs if not exist
[ ! -d ${BUILD_DIR} ] && mkdir -p ${BUILD_DIR}

# delete old wars & move new war package to &{BUILD_DIR}
#rm -rf ${BUILD_DIR}/*
mv -f ${MANAGE_SOURCE_DIR}/wzc-api/target/api.war ${BUILD_DIR}


# rsync war to remote server
    rsync -az --delete --password-file=/etc/rsync.pass ${BUILD_DIR}/ ${SYNC_USER}@${REMOTE_SERVER}::$MODULE &
#    rsync -az --delete --password-file=/etc/rsync.pass ${BUILD_DIR}/ ${SYNC_USER}@${API_SERVER2}::$MODULE &
        
END_TIME=`date "+%Y%m%d-%T"`

#log
cat > /tmp/upinfo <<EOF
=========================
server:${REMOTE_SERVER}(${REMOTE_ENV})
Start at:${START_TIME}
Finish at:${END_TIME}
$GIT_MSG
Current version:${DEPLOY_VERSION}
EOF

cat /tmp/upinfo >> /Data/logs/deplog/deploy_api_${BRANCH_NAME}.log

         
echo ${DEPLOY_VERSION} > /tmp/last_version_api_${BRANCH_NAME}
# Done

exit 0
