apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: prometheus-ingress
  namespace: prometheus
spec:
  ingressClassName: contour    
  virtualhost:
    fqdn: prometheus.baway.org.cn        
  routes:
  - conditions:               
    - prefix: /            
    services:                 
    - name: prometheus
      port: 9090
