apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: kube-etcd
    app.kubernetes.io/name: kube-etcd
    k8s-app: kube-etcd
  name: kube-etcd
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: https-metrics
    port: 2381
    targetPort: 2381
    protocol: TCP
  selector:
    component: etcd
