apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jumpserver-proxy-nginx-logs-claim
  namespace: private
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
