apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jumpserver-proxy-nginx-data-claim
  namespace: jumpserver
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
