apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-proxy-nginx-config-claim
  namespace: private
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
