# 创建pvc,持久化jenkins的~/.ssh目录
# 该pvc将在jenkins-deployment.yaml中引用
# 创建该pvc资源的前提在于创建nfs storageClass
# kubectl get sc
# NAME                  PROVISIONER      AGE
# managed-nfs-storage   fuseim.pri/ifs   25h

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim-ssh
  namespace: kube-jenkins
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
