apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
data:
  proxy-connect-timeout: "90"
  proxy-read-timeout: "90"
  proxy-send-timeout: "90"
  proxy-body-size: "20480m"
  client-body-buffer-size: "128K"
  proxy-buffer-size: "128K"
  enable-underscores-in-headers: "true"
