kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ingress-config-pvc
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: "nfs-storage-ingress-nginx"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ingress-log-pvc
  namespace: ingress-nginx
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "nfs-storage-ingress-nginx"
