apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ecshop-config-claim
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
