apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: gitlab-http
    port: 80
    targetPort: gitlab-http
  - name: gitlab-https
    port: 443
    targetPort: gitlab-https
  - name: gitlab-ssh
    port: 22
    targetPort: gitlab-ssh
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gitlab
spec:
  serviceName: "gitlab"
  replicas: 2
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:12.4.6-ce.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: gitlab-ssh
          protocol: TCP
        - containerPort: 80
          name: gitlab-http
          protocol: TCP
        - containerPort: 443
          name: gitlab-https
          protocol: TCP
        volumeMounts:
        - name: gitlabhome
          mountPath: /var/opt/gitlab
  volumeClaimTemplates:
  - metadata:
      name: gitlabhome
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-nfs-storage"
      resources:
        requests:
          storage: 10Gi
