---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginxv3
  name: nginxv3
  namespace: public
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      version: v3
  template:
    metadata:
      labels:
        app: nginx
        version: v3
    spec:
      imagePullSecrets:
      - name: shidg-ali-registry
      containers:
      - name: nginxv3
        image: registry.cn-hangzhou.aliyuncs.com/shidg/nginx:1.22.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-root
          mountPath: /usr/share/nginx/html
      volumes:
      - name: web-root
        persistentVolumeClaim:
          claimName: gray-nginx-3
