apiVersion: v1
kind: Service
metadata:
  name: gray
  namespace: public
spec:
  ports:
  - port: 8008 
    targetPort: 80
    protocol: TCP
    name: http-8008
  selector:
    app: nginx
  type: ClusterIP

