pipeline {
    agent none
    stages {
        stage('checkout') {
            agent any
            options {
                timeout(time: 15, unit: 'SECONDS')
            }
            steps {
                checkout scm
            }
        }
        stage('build') {
            agent {
                label 'test'
            }
            steps {
                sh "docker images"
                sh "docker run --rm --name maven maven:3.6.3-jdk-8 mvn --version"
                sh "sleep 60"
            }
        }
    }
}
