apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: kube-ops
  labels:
    app: jenkins
spec:
  type: NodePort
  selector:
    app: jenkins
  ports:
  - name: jenkins-web
    port: 8080
    targetPort: jenkins-web
    nodePort: 30001
  - name: jenkins-agent
    port: 50000
    targetPort: jenkins-agent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      serviceAccount: jenkins
      containers:
        - name: jenkins
          image: jenkins:2.60.3
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: jenkins-web
              protocol: TCP
            - containerPort: 50000
              name: jenkins-agent
              protocol: TCP
          volumeMounts:
            - name: jenkinshome
              mountPath: /var/jenkins_home
      volumes:
        - name: jenkinshome
          persistentVolumeClaim:
            claimName: jenkins-claim
