# 创建pvc,持久化jenkins数据
# 该pvc将在jenkins-deployment.yaml中引用
# 创建该pvc资源的前提在于创建nfs storageClass
# kubectl get sc
# NAME                  PROVISIONER      AGE
# managed-nfs-storage   fuseim.pri/ifs   25h

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jenkins-claim
  namespace: kube-ops
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: "managed-nfs-storage"
