apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: zabbix-ingress
spec:
  ingressClassName: contour    
  virtualhost:
    fqdn: zabbix.baway.org.cn        
  routes:
  - conditions:               
    - prefix: /            
    services:                 
    - name: zabbix-web
      port: 8080
