apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
  namespace: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-dep
  template:
    metadata:
      labels:
        app: grafana-dep
    spec:
      nodeName: k8s-node3
      containers:
      - image: grafana/grafana
        imagePullPolicy: IfNotPresent
        #command:
        #  - "tail"
        #  - "-f"
        #  - "/dev/null"
        securityContext:
          allowPrivilegeEscalation: false
          runAsUser: 0
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: data
        - mountPath: "/usr/share/grafana/conf"
          name: conf
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grafana-pvc
      - name: conf
        persistentVolumeClaim:
          claimName: grafana-conf
        
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: prometheus
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: grafana-dep
