kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: grafana-conf
  namespace: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "nfs-storage"
