apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - name: mogodb
    port: 27017
    targetPort: 27017
    nodePort: 30022
  selector:
    app: mongodb
  type: NodePort

