---
apiVersion: v1
kind: Endpoints
metadata:
  name: harbor
subsets:
- addresses:
  - ip: 172.27.3.210
  ports:
  - port: 80
    name: harbor
---
apiVersion: v1
kind: Service
metadata:
  name: harbor
spec:
  ports:
  - port: 8001
    name: harbor
    protocol: TCP
    targetPort: harbor
