# 手动生成ingress所需要的secret,该secret中包含了ssl证书的信息(crt & key)
# 引用该secret的ingress资源需要和该secret在同一namespace
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: default
data:
  tls.crt: <cat your.crt|base64>
  tls.key: <cat your.key|base64>
type: kubernetes.io/tls
