# Deployment 方式部署jenkins，并以Service形式向外暴露端口
# Deployment.spec.template.spec下添加了两条hostAliases，目的在于解决插件安装问题
# 

apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins
spec:
  selector:
    app: jenkins
  ports:
  - name: jenkins-web
    port: 8080
    targetPort: jenkins-web
  - name: jenkins-agent
    port: 50000
    targetPort: jenkins-agent

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      serviceAccountName: jenkins
      serviceAccount: jenkins
      containers:
        - name: jenkins
          image: jenkinsci/blueocean:1.21.0
          securityContext:
            runAsUser: 0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: jenkins-web
              protocol: TCP
            - containerPort: 50000
              name: jenkins-agent
              protocol: TCP
          volumeMounts:
            - name: jenkinshome
              mountPath: /var/jenkins_home
            - name: docker-sock
              mountPath: /var/run/docker.sock
      hostAliases:
      - ip: 192.168.0.100
        hostnames:
        - updates.jenkins-ci.org
        - mirrors.jenkins-ci.org
      - ip: 127.0.0.1
        hostnames:
        - www.google.com
        - google.com

      volumes:
        - name: jenkinshome
          hostPath:
            path: /Users/shidegang/work/docker_volumes/jenkins
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
