apiVersion: v1
kind: Service
metadata:
  name: mysqld
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
  - port: 3306
    name: mysqld
    targetPort: mysqld
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.18
        imagePullPolicy: IfNotPresent
        ports:
          - name: mysqld
            containerPort: 3306
            protocol: TCP
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/mysql
          - name: db-conf
            mountPath: /etc/mysql
      volumes:
      - name: db-data
        hostPath:
          path: /Users/shidegang/work/docker_volumes/mysqld
      - name: db-conf
        hostPath:
          path: /Users/shidegang/work/docker_configurations/mysqld

