# 创建pvc,持久化gitlab 配置文件
# 该pvc将在gitlab-deployment.yaml中引用
# 创建该pvc资源的前提在于创建nfs storageClass
# kubectl get sc
# NAME                  PROVISIONER      AGE
# managed-nfs-storage   fuseim.pri/ifs   25h

kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gitlab-claim-conf
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: "managed-nfs-storage"
