apiVersion: v1
kind: Service
metadata:
  name: gitlab
  labels:
    app: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
  - name: gitlab-http
    port: 80
    nodePort: 30080
    targetPort: gitlab-http
  - name: gitlab-https
    port: 443
    nodePort: 30443
    targetPort: gitlab-https
  - name: gitlab-ssh
    nodePort: 30022
    port: 22
    targetPort: gitlab-ssh
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      serviceAccount: gitlab
      serviceAccountName: gitlab
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:12.5.4-ce.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 22
          name: gitlab-ssh
          protocol: TCP
        - containerPort: 30080
          name: gitlab-http
          protocol: TCP
        - containerPort: 443
          name: gitlab-https
          protocol: TCP
        volumeMounts:
        - name: gitlabhome
          mountPath: /var/opt/gitlab
        - name: gitlabconf
          mountPath: /etc/gitlab
      volumes:
      - name: gitlabhome
        persistentVolumeClaim:
          claimName: gitlab-claim
      - name: gitlabconf
        persistentVolumeClaim:
          claimName: gitlab-claim-conf
