apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: istio-system
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
        - static_configs:
          - targets: ["alertmanager:9093"]
    rule_files:
      - /etc/prometheus/rules.yml
    scrape_configs:
    - job_name: nginx-vts-exporter
      scrape_interval: 30s
      static_configs:
        - targets:
          - jenkins-proxy-svc.private:9913
    - job_name: nginx-prometheus-exporter
      scrape_interval: 30s
      static_configs:
        - targets:
          - jenkins-proxy-svc.private:9113

    - job_name: 'redis_exporter_targets'
      static_configs:
        - targets:
          - redis://10.203.43.151:6379
          - redis://10.203.43.151:6380
          - redis://10.203.43.152:6379
          - redis://10.203.43.152:6380
          - redis://10.203.43.153:6379
          - redis://10.203.43.153:6380
      metrics_path: /scrape
      relabel_configs:
        - source_labels: [__address__]
          target_label: __param_target
        - source_labels: [__param_target]
          target_label: instance
        - target_label: __address__
          replacement: redis-exporter.prometheus:9121

    - job_name: 'redis_exporter'
      static_configs:
        - targets:
          - redis-exporter.prometheus:9121


