filebeat.inputs:
- type: filestream
  id: logs-of-docker-nginx
  enabled: true
  paths:
    - /var/log/nginx/access.log


output.logstash:
  hosts: ["localhost:5044"]


# 自定义filebeat的运行日志
logging.to_files: true
logging.level: info
logging.files:
  path: /var/log/filebeat
  name: filebeat.log
