---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kuboard
  name: kuboard
  namespace: private
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuboard
  template:
    metadata:
      labels:
        app: kuboard
    spec:
      dnsPolicy: "ClusterFirstWithHostNet"
      nodeName: k8s-node3
      containers:
      - name: kuboard
        image: eipwork/kuboard:v3.5.2.7
        imagePullPolicy: IfNotPresent
        env:
        - name: KUBOARD_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: kuboard
              key: KUBOARD_ENDPOINT
        - name: KUBOARD_AGENT_SERVER_UDP_PORT
          valueFrom:
            configMapKeyRef:
              name: kuboard
              key: KUBOARD_AGENT_SERVER_UDP_PORT
        - name: KUBOARD_AGENT_SERVER_TCP_PORT
          valueFrom:
            configMapKeyRef:
              name: kuboard
              key: KUBOARD_AGENT_SERVER_TCP_PORT
        - name: KUBOARD_LOGIN_TYPE
          value: "ldap"
        - name: LDAP_HOST
          value: "openldap:389"
        - name: LDAP_SKIP_SSL_VERIFY
          value: "true"
        - name: LDAP_BIND_DN
          value: "cn=admin,dc=baway,dc=org,dc=cn"
        - name: LDAP_BIND_PASSWORD
          value: "admin"
        - name: LDAP_BASE_DN
          value: "dc=baway,dc=org,dc=cn"
        - name: LDAP_FILTER
          value: "(objectClass=posixAccount)"
        - name: LDAP_ID_ATTRIBUTE    # 如果使用用户名登录,这里修改成uid
          value: "mail"
        - name: LDAP_USER_NAME_ATTRIBUTE
          value: "mail"             # 如果使用用户名登录,这里修改成uid
        - name: LDAP_EMAIL_ATTRIBUTE
          value: "mail"
        - name: LDAP_DISPLAY_NAME_ATTRIBUTE
          value: "cn"
        - name: LDAP_GROUP_SEARCH_BASE_DN
          value: "dc=baway,dc=org,dc=cn"
        - name: LDAP_GROUP_SEARCH_FILTER
          value: "(objectClass=posixGroup)"
        - name: LDAP_USER_MACHER_USER_ATTRIBUTE
          value: "gidNumber"
        - name: LDAP_USER_MACHER_GROUP_ATTRIBUTE
          value: "gidNumber"
        - name: LDAP_GROUP_NAME_ATTRIBUTE
          value: "cn"
        - name: KUBOARD_ROOT_USER
          value: "94586572@qq.com"   # 如果使用用户名登录,这里修改成用户名
        - name: KUBOARD_DISABLE_AUDIT
          value: "true"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 10081
          name: tcp-api
          protocol: TCP
        - containerPort: 10081
          name: udp-api
          protocol: UDP
        volumeMounts:
          - name: kuboard-data
            mountPath: /data
      volumes:
      - name: kuboard-data
        hostPath:
          path: /home/shidegang/kuboard_data

---
apiVersion: v1
kind: Service
metadata:
  name: kuboard
  namespace: private
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: kuboard
  type: ClusterIP
