apiVersion: v1
kind: Service
metadata:
  name: httpd
  labels:
    k8s/app: nginx
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - name: http
      port: 80
      targetPort: http
    - name: https
      port: 443
      targetPort: https

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx@sha256:2911ad2d54f4cf4dc7ad21af122c1eefce16836a34be751c63351ca1fb452d57
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        volumeMounts:
        - name: wwwdata
          mountPath: /usr/share/nginx/html
        - name: wwwconf
          mountPath: /etc/nginx
      volumes:
      - name: wwwdata
        hostPath:
          path: /Users/shidg/Downloads
      - name: wwwconf
        hostPath:
          path: /Users/shidg/work/docker_configurations/nginx
