# grafana可视化
# dashboard 10000  3131  7249 315
apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  type: NodePort
  selector:
    app: grafana
  ports:
  - name: grafana
    protocol: TCP
    port: 3000
    targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana
        ports:
        - containerPort: 3000
          protocol: TCP
