# 部署prometheus/alertmanager并作为service对外暴露
# prometheus和alertmanager两个container放到了一个pod中
# 同一个pod中的不同容器共享网络命名空间，可以使用localhost互相通信
# 在部署该资源时，确保已经部署了以下资源：
# prometheus-rbac-setup.yaml(访问授权) 
# prometheus-config.yaml(configMap prometheus的主配置文件和告警规则文件)
# alertmanager-config.yaml(configMap  alertmanager的配置文件)

---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus  
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090
    nodePort: 30090

---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  labels:
    name: alertmanager
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
  - name: alertmanager
    protocol: TCP
    port: 9093
    targetPort: 9093
    nodePort: 30093

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      name: prometheus
      labels:
        app: prometheus
    spec:
      # serviceAccount  访问授权
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus:v2.14.0
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        - --web.enable-lifecycle
        ports:
        - name: prometheus
          containerPort: 9090
          protocol: TCP
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus  
        - name: localtime
          mountPath: /etc/localtime
      - name: alertmanager
        image: prom/alertmanager:v0.20.0
        imagePullPolicy: IfNotPresent
        args:
        - --config.file=/etc/alertmanager/alertmanager.yml
        ports:
        - name: alertmanager
          containerPort: 9093
          protocol: TCP
        volumeMounts:
        - name: localtime
          mountPath: /etc/localtime
        - name: alertmanager-config
          mountPath: /etc/alertmanager

      volumes:
      - name: localtime
        hostPath: 
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: prometheus-config
        configMap:
          name: prometheus-config    
          items:
          - key: prometheus
            path: prometheus.yml
          - key: rules
            path: rules.yml
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
