# 部署prometheus并作为service对外暴露
# 在部署该资源时，确保已经部署了prometheus-rbac-setup.yml(访问授权) 和 prometheus-config.yml(配置文件)
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus  
  ports:
  - name: prometheus
    protocol: TCP
    port: 9090
    targetPort: 9090

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      # serviceAccount  访问授权
      serviceAccountName: prometheus
      serviceAccount: prometheus
      containers:
      - name: prometheus
        image: prom/prometheus
        command: 
        - /bin/prometheus
        args:
        - --config.file=/etc/prometheus/prometheus.yml
        ports:
        - containerPort: 9090
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/prometheus  
          name: prometheus-config
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config    
