apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: download
  namespace: istio-system
spec:
  hosts:
  - download.baway.org.cn
  gateways:
    - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: / 
    route:
    - destination:
        port:
          number: 8008
        host: jenkins-proxy-svc.private.svc.cluster.local
