apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gitlab-http
  namespace: istio-system
spec:
  hosts:
  - git.baway.org.cn
  gateways:
    - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: gitlab.private.svc.cluster.local
