apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: kuboard
  namespace: istio-system
spec:
  hosts:
  - kuboard.baway.org.cn
  gateways:
    - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 80
        host: kuboard.private.svc.cluster.local
