apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ldap-tcp
  namespace: istio-system
spec:
  hosts:
  - ldap.baway.org.cn
  gateways:
    - gateway-tcp-for-ldap
  tcp:
  - match:
    - port: 389
    route:
    - destination:
        port:
          number: 389
        host: openldap.private.svc.cluster.local
