apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: nginx
  namespace: istio-system
spec:
  hosts:
  - nginx.baway.org.cn
  gateways:
  - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: nginx.baway.svc.cluster.local
