apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: rabbitmq
  namespace: istio-system
spec:
  hosts:
  - rabbitmq.baway.org.cn
  gateways:
  - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 15672
        host: rabbitmq-svc.mall-swarm.svc.cluster.local
