apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: screego-https
  namespace: istio-system
spec:
  hosts:
  - screego.baway.org.cn
  gateways:
  - baway-gateway-http
  tls:
  - match:
    - port: 443
      sniHosts:
      - screego.baway.org.cn
    route:
    - destination:
        port:
          number: 5050
        host: screego.private.svc.cluster.local
