apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: screego-tcp
  namespace: istio-system
spec:
  hosts:
  - screego.baway.org.cn
  tcp:
  - match:
    - port: 443
    route:
    - destination:
        port:
          number: 5050
        host: screego.private.svc.cluster.local
