apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: screego-http
  namespace: istio-system
spec:
  hosts:
  - screego.baway.org.cn
  gateways:
    - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 5050
        host: screego.private.svc.cluster.local
