apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: zabbix-server-tcp
  namespace: istio-system
spec:
  hosts:
    - 10.203.43.230
  gateways:
    - gateway-tcp-for-zabbix
  tcp:
  - match:
    - port: 10051
    route:
    - destination:
        port:
          number: 10051
        host: zabbix-server.default.svc.cluster.local
