apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: zabbix
  namespace: istio-system
spec:
  hosts:
  - zabbix.baway.org.cn
  gateways:
    - baway-gateway-http
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: 8080
        host: zabbix-web.default.svc.cluster.local
