#!/usr/local/bin/python3
# -*- coding: utf-8 -*-#
'''
author: -- shidegang --
Created Time: 2019-08-28 10:43:17
'''

#https://www.cnblogs.com/wupeiqi/articles/5713315.html
#https://www.cnblogs.com/wupeiqi/articles/5713323.html
#https://www.cnblogs.com/wupeiqi/articles/5729934.html
#https://www.cnblogs.com/wupeiqi/articles/5716963.html

