kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ldap-conf
  namespace: private
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-storage
