apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: alertmanager-ingress
  namespace: monitoring
spec:
  ingressClassName: contour    
  virtualhost:
    fqdn: alertmanager.baway.org.cn        
  routes:
  - conditions:               
    - prefix: /            
    services:                 
    - name: alertmanager-main
      port: 9093
