apiVersion: v1
kind: Service
metadata:
  name: mysql8
  namespace: default
  labels:
    app: mysql8
spec:
  selector:
    app: mysql8
  ports:
  - name: mysql
    port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 30036
  - name: zabbix-agent
    port: 10050
    targetPort: 10050
    nodePort: 30050
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql8
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql8
  template:
    metadata:
      labels:
        app: mysql8
    spec:
      nodeName: k8s-node2
      containers:
      - name: mysql
        image: mysql:8.0.33
        imagePullPolicy: IfNotPresent
        args:
        - "--character-set-server=utf8mb4"
        - "--collation-server=utf8mb4_bin"
        - "--default-authentication-plugin=mysql_native_password"
        env:
        - name: MYSQL_DATABASE
          value: "zabbix"
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          value: "zabbix"
        - name: MYSQL_ROOT_PASSWORD
          value: "123456"
        ports:
        - containerPort: 3306
          name: mysql
          protocol: TCP
        volumeMounts:
        - name: timezone
          mountPath: /etc/localtime
        - name: data
          mountPath: /var/lib/mysql
      terminationGracePeriodSeconds: 20
      volumes:
      - name: timezone
        hostPath:
          path: /usr/share/zoneinfo/Asia/Shanghai
      - name: data
        hostPath:
          path: /data/volume/mysql/zabbix
