apiVersion: apps/v1
kind: Deployment
metadata:
  name: jumpserver-redis6
  namespace: jumpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jumpserver-redis6
  template:
    metadata:
      labels:
        app: jumpserver-redis6
    spec:
      containers:
      - image: redis:6.0.9
        command: ["redis-server","/etc/redis/redis.conf"]
        name: redis
        ports:
        - containerPort: 6379        
        volumeMounts:
        - name: redis6-config
          mountPath: /etc/redis/redis.conf
          subPath: redis.conf
        - name: redis6-data
          mountPath: /data
      volumes:
      - name: redis6-config
        configMap:
          name: redis6-config
      - name: redis6-data
        persistentVolumeClaim:
          claimName: redis6-data-claim
