apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis6-data-claim
  namespace: jumpserver
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
