apiVersion: v1
kind: Service
metadata:
  labels:
    app: mysql-exporter
  name: mysql-exporter
  namespace: prometheus
spec:
  ports:
  - port: 9104
    protocol: TCP
    targetPort: 9104
  selector:
    app: mysql-exporter
  type: ClusterIP
