apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: gray-nginx-destination-rule
  namespace: istio-system
spec:
  host: gray.public.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
    trafficPolicy:
      loadBalancer:
        simple: ROUND_ROBIN
  - name: v3
    labels:
      version: v3
