apiVersion: v1
kind: Pod
metadata:
  name: pepa
spec:
  containers:
  - name: centos
    image: centos
    imagePullPolicy: IfNotPresent

    volumeMounts:
    - mountPath: /var/www/html
      name: www-volume
    args:
    - /bin/bash
    - -c
    - ls /var/www/html/;sleep 20000
  volumes:
  - name: www-volume
    emptyDir: {}
