apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
  namespace: prometheus
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: blackbox-exporter
  template:
    metadata:
      labels:
        app: blackbox-exporter
    spec:
      imagePullSecrets:
      - name: shidg-ali-registry
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/shidg/blackbox-exporter:0.25.0
        imagePullPolicy: IfNotPresent
        name: blackbox-exporter
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: blackbox-exporter
  name: blackbox-exporter
  namespace: prometheus
spec:
  ports:
  - port: 9115
    protocol: TCP
    targetPort: 9115
  selector:
    app: blackbox-exporter
  type: ClusterIP
