apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: ceph-ingress
  namespace: rook-ceph
spec:
  ingressClassName: contour    
  virtualhost:
    fqdn: ceph.baway.org.cn        
  routes:
  - conditions:               
    - prefix: /            
    services:                 
    - name: rook-ceph-mgr-dashboard
      port: 7000
