apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-pv-claim
  labels:
    app: cephfs
spec:
  storageClassName: rook-cephfs
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
